# Generated by Django 4.2.2 on 2023-06-16 23:32

from django.db import migrations, models
import proposals.models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_alter_proposal_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='cpf',
            field=models.PositiveIntegerField(validators=[proposals.models.validate_cpf]),
        ),
    ]
